### ISSUE TITLE
Build?

### ISSUE THREAD

**Issue by dethier1958** [m1ga/ti.print#1]
Now that Titanium 11.0.0.GA is out, do you have a build of ti.print so I can try to add that module to my Android app? Thanks!

**Comment by m1ga** [comment]
oh sorry. of course: https://github.com/m1ga/ti.print/releases/tag/1.0.0

**Comment by dethier1958** [comment]
Thanks! I got it working in my app! Very simple to use.

![print](https://user-images.githubusercontent.com/6359232/178055797-a721bdf4-734c-4d21-a43e-269df1aa1f20.png)

**Comment by m1ga** [comment]
awesome, good to hear :+1:
